FROM centos
MAINTAINER "Sally O'Malley <somalley at redhat dot com>
ENV container docker

LABEL "Name"="atomic-test-1"

LABEL RUN "/usr/bin/docker run -t --user \${SUDO_UID}:\${SUDO_GID} \${OPT1}  -v \${LOGDIR}:/var/log -v \${DATADIR}:/var/lib \$OPT2 --name \${NAME} \${IMAGE} \$OPT3 echo I am the run label." 

LABEL INSTALL "docker \${OPT1} run  -v \${CONFDIR}:/etc/${NAME} -v \${LOGDIR}:/var/log/${NAME} -v \${DATADIR}:/var/lib/${NAME} \$OPT2 --name \${NAME} \${IMAGE} \$OPT3 echo I am the install label."
